### ISSUE TITLE
Line endings vs. Git conflicts

### ISSUE THREAD

**Issue by catalinpreda** [madalinoprea/django-sales-event#1]
After Vagrant was initialized, Git sees all the files in salesevents/static/admin/css and salesevents/static/admin/js (admin/js/admin excluded) as modified. The reason seems to be different line endings. These kind of changes will possibly be commited back and forth as we commit, push and pull, I think?

**Comment by madalinoprea** [comment]
Change your laptop.. 

I've removed salesevents/static folder from repository because it was a mistake. This folder is automatically constructed by collectstatic command executed when the VM starts.

We shouldn't add anything to the folder and we should MEDIA_DIR or use static/ folder of our apps.

Related to line endings issue, you should switch to Mac or install Git for windows without checking automatically to convert line breaks.
